const formosa = {
  nombre: "Formosa",
  distanciaEntreProvincias: [
    { provincia: "Buenos Aires", distancia: 1329 },
    { provincia: "Catamarca", distancia: 691 },
    { provincia: "Chaco", distancia: 348 },
    { provincia: "Chubut", distancia: 2541 },
    { provincia: "Córdoba", distancia: 713 },
    { provincia: "Corrientes", distancia: 327 },
    { provincia: "Jujuy", distancia: 1169 },
    { provincia: "La Pampa", distancia: 1495 },
    { provincia: "La Rioja", distancia: 795 },
    { provincia: "Mendoza", distancia: 1436 },
    { provincia: "Misiones", distancia: 535 },
    { provincia: "Neuquén", distancia: 1811 },
    { provincia: "Río Negro", distancia: 1866 },
    { provincia: "Salta", distancia: 1070 },
    { provincia: "San Juan", distancia: 1262 },
    { provincia: "San Luis", distancia: 1322 },
    { provincia: "Santa Cruz", distancia: 3213 },
    { provincia: "Santa Fe", distancia: 881 },
    { provincia: "Santiago del Estero", distancia: 433 },
    { provincia: "Tierra del Fuego", distancia: 4259 },
    { provincia: "Tucumán", distancia: 877 },
  ],
};
module.exports = formosa;
