const santiagoDelEstero = {
  nombre: "Santiago del Estero",
  distanciaEntreProvincias: [
    { provincia: "Buenos Aires", distancia: 1040 },
    { provincia: "Catamarca", distancia: 258 },
    { provincia: "Chaco", distancia: 85 },
    { provincia: "Chubut", distancia: 2210 },
    { provincia: "Córdoba", distancia: 424 },
    { provincia: "Corrientes", distancia: 4 },
    { provincia: "Entre Ríos", distancia: 871 },
    { provincia: "Formosa", distancia: 433 },
    { provincia: "Jujuy", distancia: 736 },
    { provincia: "La Pampa", distancia: 1016 },
    { provincia: "La Rioja", distancia: 362 },
    { provincia: "Mendoza", distancia: 1003 },
    { provincia: "Misiones", distancia: 314 },
    { provincia: "Neuquén", distancia: 1404 },
    { provincia: "Río Negro", distancia: 1459 },
    { provincia: "Salta", distancia: 637 },
    { provincia: "San Juan", distancia: 769 },
    { provincia: "San Luis", distancia: 620 },
    { provincia: "Santa Cruz", distancia: 2660 },
    { provincia: "Santa Fe", distancia: 736 },
    { provincia: "Tierra del Fuego", distancia: 3706 },
    { provincia: "Tucumán", distancia: 462 },
  ],
};
module.exports = santiagoDelEstero;
