const tucuman = {
  tucuman: {
    nombre: "Tucumán",
    distanciaEntreProvincias: [
      { provincia: "Buenos Aires", distancia: 1316 },
      { provincia: "Catamarca", distancia: 163 },
      { provincia: "Chaco", distancia: 795 },
      { provincia: "Chubut", distancia: 2326 },
      { provincia: "Córdoba", distancia: 621 },
      { provincia: "Corrientes", distancia: 714 },
      { provincia: "Entre Ríos", distancia: 1010 },
      { provincia: "Formosa", distancia: 950 },
      { provincia: "Jujuy", distancia: 218 },
      { provincia: "La Pampa", distancia: 1360 },
      { provincia: "La Rioja", distancia: 358 },
      { provincia: "Mendoza", distancia: 790 },
      { provincia: "Misiones", distancia: 834 },
      { provincia: "Neuquén", distancia: 1899 },
      { provincia: "Río Negro", distancia: 1954 },
      { provincia: "Salta", distancia: 307 },
      { provincia: "San Juan", distancia: 856 },
      { provincia: "San Luis", distancia: 1032 },
      { provincia: "Santa Cruz", distancia: 2830 },
      { provincia: " Santa Fe", distancia: 994 },
      { provincia: "Santiago del Estero", distancia: 271 },
      { provincia: " Tierra del Fuego", distancia: 3876 },
    ],
  },
};
module.exports = tucuman;
